name: ci

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  node-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: project/services/api-gateway
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm run build

  python-fraud:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: project/services/fraud-service
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: pytest
